# This file was generated by GoReleaser. DO NOT EDIT.
cask "cc-probeline" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "ff04b22c16a63bec6db04b6bda19e21124855879f942ff303074479c2a90419f"
      url "https://github.com/labzink/cc-probeline/releases/download/v#{version}/cc-probeline_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1a655b67905ab5141b73fd220a9a2dcc4880b0684c554c661862bfac2993ab1f"
      url "https://github.com/labzink/cc-probeline/releases/download/v#{version}/cc-probeline_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2363b4db044e2271482d41d05883344d4884d356ba1d599eebb56e29ee3d909d"
      url "https://github.com/labzink/cc-probeline/releases/download/v#{version}/cc-probeline_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "56f1abba76af18bd648bc5ddab0a57b46b0606b5c41d0400819732638252f6ad"
      url "https://github.com/labzink/cc-probeline/releases/download/v#{version}/cc-probeline_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cc-probeline"
  desc "Status line plugin for Claude Code — model, tokens, cost, subagents"
  homepage "https://github.com/labzink/cc-probeline"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cc-probeline"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cc-probeline"]
    end
  end

  # No zap stanza required

end
