# This file was generated by GoReleaser. DO NOT EDIT.
cask "cc-probeline" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "c43b0bf27d0eebd8a66554e3f0a4aeb2b7119b2bb0a9b7b5a7bfa424d6b3b2bd"
      url "https://github.com/labzink/cc-probeline/releases/download/v#{version}/cc-probeline_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "47630ff9ddbe24eb2a44335caab4d3e58b39c3c881cfbc25ffcd6e547adb8812"
      url "https://github.com/labzink/cc-probeline/releases/download/v#{version}/cc-probeline_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9225429cf8bbdc6355511d74b0a87f395ee2588d7a3212143ed5a0a24de9bbe3"
      url "https://github.com/labzink/cc-probeline/releases/download/v#{version}/cc-probeline_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a71e5382abb30fab9797b192eaa5e92db9a49978f5d7472dd062c21f5e0564ad"
      url "https://github.com/labzink/cc-probeline/releases/download/v#{version}/cc-probeline_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cc-probeline"
  desc "Status line plugin for Claude Code — model, tokens, cost, subagents"
  homepage "https://github.com/labzink/cc-probeline"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cc-probeline"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cc-probeline"]
    end
    system_command "#{staged_path}/cc-probeline",
                   args: ["install", "--merge-settings",
                          "--binary-path", "#{HOMEBREW_PREFIX}/bin/cc-probeline",
                          "--if-absent"]
    ohai "cc-probeline: restart Claude Code to load the status line."
  end

  uninstall_preflight do
    system_command "#{staged_path}/cc-probeline", args: ["uninstall"]
  end

  # No zap stanza required

end
