# This file was generated by GoReleaser. DO NOT EDIT.
cask "cc-probeline" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "d17b08a6b87f24a387eb1e3e88780df6a800fdb87789a6d7914803614f2adccb"
      url "https://github.com/labzink/cc-probeline/releases/download/v#{version}/cc-probeline_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7ff0243cc2c5c43a1db4bd3443c7295591f8ca9f29315591f811375999c72262"
      url "https://github.com/labzink/cc-probeline/releases/download/v#{version}/cc-probeline_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "cce91ced413d5d05b5162bead6de37058a97706a90f577946827fc998718cca8"
      url "https://github.com/labzink/cc-probeline/releases/download/v#{version}/cc-probeline_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c9595808a42f32f945a23c76f0e0198a3d05692bf207848b2fb7933456bd3c0b"
      url "https://github.com/labzink/cc-probeline/releases/download/v#{version}/cc-probeline_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cc-probeline"
  desc "Status line plugin for Claude Code — model, tokens, cost, subagents"
  homepage "https://github.com/labzink/cc-probeline"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cc-probeline"

  # No zap stanza required

end
